version: "3"

networks:
  main:

services:

  zookeeper:
    image: bitnami/zookeeper:3.8
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    volumes:
      - zookeeper_data:/bitnami
    networks:
      main:
        aliases:
          - zookeeper

  kafka:
    image: bitnami/kafka:3.1
    networks:
      main:
        aliases:
          - kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    ports:
      - 9092:9092

volumes: 
  zookeeper_data: